on:
  - workflow_dispatch

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: Go build
        id: build
        shell: bash
        run: |
          go build -o out/hello-world

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: artifactz
          path: out/

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: artifactz
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
